baseURL = "http://mdl.wtf/"
languageCode = "en-us"
title = "MDL - Talent Hub Blog"

[Params]
  keywords = "MDL,blockchain,talents,models,technology,app,IPFS"
  description = "Blog of MDL Talent Hub. We create blockchain powered platform for talent sourcing industry."
  telegram = "https://t.me/MDL_Talent_Hub"